env:
  global:
    secure: JRXEnXa63AkesW0lbKNtnO1u5mk/0P3WGJAyFYaVN3Te6TQMHyNz4x8fREkprPou4x/qfXFniuxx4OVE3MyCZjU1Mm+sOZ27iY1jVy1zwG28/5TUcm7YYG+q2oMIrSIp4akEMnP0RneSGO6Eg94iOk90cjKLRZuCktnrbCAVglFj6k5reqI/CTXiUwckHO1w0mHTiOfiZ0w6KAzrx2GV5FuGTFmpJaQkRKu0ZdeyKSZkCC4cjPv59XuslDcfuqJGvmFHug0uxPDZ0M6H7UgsQjxrXibtR7sUahy4TuZNZOCOCeWZy6xcgGRk5CUtQlv7N2RYff2A4zXNFk4f7VPKm/8OcEX2vPPt+D6mSc97YXlMmTc9a7VA6BvF9yG/uki15Go/wJOfHjNLQONg7N9uw23wsj6oGbDMj7U1aYxofb1bRqJSggyx92ShzvhVGC1ikmwOY7XECLAiD+oJamVRy9r+iXgIk/rBSy4uJxgCx96iX4ha06mJfJKqFrKUqc+33YF4SNrTwetulEU/gff9/jKQlocKSBye2u7zuz3tp+zZaxdRICzhbEgd4SuHtEiY+8SV/ylcFrm1+sjG25FWhnKN7dN2eTYfXP/wqth8HvySa5+YFlJ6E4z9F6QJTmdCCyERywk/ohyAJkh/h3Yjmok2kIEeuRgjv5xssR6fKfk=

dist: bionic
language: c
compiler:
  - clang
  - gcc
before_install:
  - sudo apt-get update
  - sudo apt-get -y install cmake doxygen

before_script:
  - mkdir build && cd build
  - cmake -DCMAKE_BUILD_TYPE=RELEASE -DCMAKE_INSTALL_PREFIX:PATH=$TRAVIS_BUILD_DIR/build/install $TRAVIS_BUILD_DIR

script:
  - make
  - make doc
  - sudo make install

deploy:
  provider: pages
  skip_cleanup: true
  github_token: "$GITHUB_TOKEN"
  keep_history: true
  local_dir: "$TRAVIS_BUILD_DIR/build/doc/html"
  edge: true
  on:
    branch: master
