/*
 * Generated by dtrace(1M).
 */

#ifndef	_DTRACE_H
#define	_DTRACE_H

#include <unistd.h>

#ifdef	__cplusplus
extern "C" {
#endif

#include <sys/sdt.h>

#if _DTRACE_VERSION

#define	WORLEYNOISE_OVERFLOWED() \
	__dtrace_worleynoise___overflowed()
#ifndef	__sparc
#define	WORLEYNOISE_OVERFLOWED_ENABLED() \
	__dtraceenabled_worleynoise___overflowed()
#else
#define	WORLEYNOISE_OVERFLOWED_ENABLED() \
	__dtraceenabled_worleynoise___overflowed(0)
#endif


extern void __dtrace_worleynoise___overflowed(void);
#ifndef	__sparc
extern int __dtraceenabled_worleynoise___overflowed(void);
#else
extern int __dtraceenabled_worleynoise___overflowed(long);
#endif

#else

#define	WORLEYNOISE_OVERFLOWED()
#define	WORLEYNOISE_OVERFLOWED_ENABLED() (0)

#endif


#ifdef	__cplusplus
}
#endif

#endif	/* _DTRACE_H */
